//@ts-nocheck
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface CompanyFactoryInterface extends utils.Interface {
  functions: {
    "companies()": FunctionFragment;
    "companiesCount()": FunctionFragment;
    "createCompany(string)": FunctionFragment;
    "currentId()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "companies"
      | "companiesCount"
      | "createCompany"
      | "currentId"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "companies", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "companiesCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createCompany",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "currentId", values?: undefined): string;

  decodeFunctionResult(functionFragment: "companies", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "companiesCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createCompany",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "currentId", data: BytesLike): Result;

  events: {
    "CompanyCreated(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CompanyCreated"): EventFragment;
}

export interface CompanyCreatedEventObject {
  company: string;
  owner: string;
}
export type CompanyCreatedEvent = TypedEvent<
  [string, string],
  CompanyCreatedEventObject
>;

export type CompanyCreatedEventFilter = TypedEventFilter<CompanyCreatedEvent>;

export interface CompanyFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: CompanyFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    companies(overrides?: CallOverrides): Promise<[string[]]>;

    companiesCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    createCompany(
      name: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    currentId(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  companies(overrides?: CallOverrides): Promise<string[]>;

  companiesCount(overrides?: CallOverrides): Promise<BigNumber>;

  createCompany(
    name: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  currentId(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    companies(overrides?: CallOverrides): Promise<string[]>;

    companiesCount(overrides?: CallOverrides): Promise<BigNumber>;

    createCompany(
      name: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    currentId(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    "CompanyCreated(address,address)"(
      company?: PromiseOrValue<string> | null,
      owner?: PromiseOrValue<string> | null
    ): CompanyCreatedEventFilter;
    CompanyCreated(
      company?: PromiseOrValue<string> | null,
      owner?: PromiseOrValue<string> | null
    ): CompanyCreatedEventFilter;
  };

  estimateGas: {
    companies(overrides?: CallOverrides): Promise<BigNumber>;

    companiesCount(overrides?: CallOverrides): Promise<BigNumber>;

    createCompany(
      name: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    currentId(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    companies(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    companiesCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    createCompany(
      name: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    currentId(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
