/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Company } from "./Company";
export type { CompanyFactory } from "./CompanyFactory";
export * as factories from "./factories";
export { Company__factory } from "./factories/Company__factory";
export { CompanyFactory__factory } from "./factories/CompanyFactory__factory";
