/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Company__factory } from "./Company__factory";
export { CompanyFactory__factory } from "./CompanyFactory__factory";
